<?php

/**
 * Test class for Fw_Db_Query_Where.
 * Generated by PHPUnit on 2011-11-25 at 11:30:57.
 */
class Fw_Db_Query_WhereTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Fw_Db_Query_Where
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp($condition = null, $value = null, $cast = null) {
		if (is_null($condition)) {
			$condition = 'field = ?';
			$value = 'string';
		}

		$this->object = new Fw_Db_Query_Where($condition, $value);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	public function testString() {
		$obj = new Fw_Db_Query_Where('ababagalamaga ?');
		$this->assertEquals('ababagalamaga ?', $obj->condition);
	}

	public function testMixValue() {
		$obj = new Fw_Db_Query_Where('ababagalamaga = 123', 'value');

		$fs = $binds = array();
		$obj->appendToQuery($fs, $binds);

		$this->assertContains('(ababagalamaga = 123)', $fs);
		$this->assertEquals(array('value'), $binds);
	}

}