<?php

/**
 * Test class for Fw_Db_Query_Behaviour.
 * Generated by PHPUnit on 2011-11-23 at 02:06:43.
 */
class Fw_Db_Query_BehaviourTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Fw_Db_Query_Behaviour
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}