<?php

/**
 * Test class for Fw_Logger_Abstract.
 * Generated by PHPUnit on 2011-12-30 at 14:11:01.
 */
class Fw_Logger_AbstractTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Fw_Logger_Abstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Fw_Logger_Abstract(new Fw_Config(array()));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * 
	 */
	public function testSave() {
		$data = array('aaaa');
		$this->assertTrue($this->object->save($data) instanceof Fw_Logger_Abstract);
	}

	/**
	 * 
	 */
	public function testGetData() {
		$data = array('aaaa');
		$this->assertEquals($data, $this->object->save($data)->getData());
	}

}