<?php

/**
 * Test class for Fw_Logger.
 * Generated by PHPUnit on 2011-12-30 at 14:05:58.
 */
class Fw_Logger_FileTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Fw_Logger_File
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Fw_Logger_File(new Fw_Config(array()));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo After implementing 
	 */
	public function testPrepare() {
		$data = array('aaaa' => 'bbbb');
		$this->object->save($data);
		
		$got = $this->object->getData();
		$this->assertTrue(is_array($got));
		
		//	checking 'time' param
		$this->assertArrayHasKey('time', $got);
		$expected_time = date(Fw_Logger_File::TIME_FORMAT, strtotime($got['time']));
		$this->assertEquals($expected_time, $got['time']);
		
		//	checking 'string' param
		$this->assertArrayHasKey('string', $got);
		$this->assertEquals(print_r($data, true), $got['string']);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetData().
	 */
	public function testGetData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
