<?php

/**
 * Test class for Autoloader.
 * Generated by PHPUnit on 2011-11-22 at 00:29:38.
 */
class AutoloaderTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Autoloader
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = Autoloader::i();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		$this->object->clear();
	}

	public function testI() {
		$this->assertTrue(Autoloader::i() instanceof Autoloader);
	}

	/**
	 * 
	 */
	public function testInvokeClass() {
		$this->object->pushAutoload('Fw', PATH_FW . DIRECTORY_SEPARATOR, 'fw');
		$this->assertTrue(class_exists('Fw_Config'));
		$this->assertFalse(class_exists('FW_ConfigAbabagalamaga'));
		$this->assertFalse(class_exists('Fw_Config_Ababagalamaga'));
		
		$this->object->pushAutoload('', PATH_FW . DIRECTORY_SEPARATOR);
		$this->assertFalse(class_exists('Config'));
		$this->object->pushAutoload('', PATH_FW . DIRECTORY_SEPARATOR, false);
		$this->assertFalse(class_exists('Config'));
	}
	
	/**
	 * Testing interfaces finding
	 */
	public function testInvokeInterface() {
		$this->assertFalse(interface_exists('InterfaceConfig'));
		$this->object->pushAutoload('', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR, false);
		$this->assertTrue(interface_exists('InterfaceConfig'));
	}

}