<?php

/**
 * Test class for Fw_Db.
 * Generated by PHPUnit on 2011-11-23 at 00:17:39.
 */
class Fw_DbTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Fw_Db
	 */
	protected $object;

	/**
	 *
	 * @var Fw_Config
	 */
	protected static $configCorrect;

	/**
	 *
	 * @var Fw_Config
	 */
	protected static $configIncorrect;

	public static function setUpBeforeClass() {
		parent::setUpBeforeClass();

		self::$configCorrect = new Fw_Config(PATH_CONFIG . DIRECTORY_SEPARATOR . 'config.php');

		self::$configIncorrect = new Fw_Config(array(
					'driver' => 'mysql',
					'server' => 'ababagalamaga',
					'port' => '3306',
					'name' => 'fw_testing',
					'user' => 'root',
					'password' => 'root',
					'encoding' => 'utf8'
				));
	}

	/**
	 * 
	 */
	protected function setUp() {
		$this->object = Fw_Db::i(true);
	}

	/**
	 * @expectedException Fw_Exception_Db_Connection
	 */
	public function testConnectIncorrect() {
		$this->object->connect(self::$configIncorrect);
	}

	/**
	 * 
	 */
	public function testConnectCorrect() {
		$this->assertTrue($this->object->connect(self::$configCorrect->db) instanceof Fw_Db);
	}

	public function testQuery() {
		$this->assertTrue($this->object->query() instanceof Fw_Db_Query);
	}

	public function testSetGetLogger() {
		$this->assertTrue($this->object->setLogger(new Fw_Logger_Db(new Fw_Config(array()), function($data) {
									return $data;
								})) instanceof Fw_Db);
		$this->assertTrue($this->object->Logger instanceof Fw_Logger_Db);
	}

	public function testUnsetLogger() {
		$this->assertTrue($this->object->setLogger(new Fw_Logger_Db(new Fw_Config(array()), function($data) {
									return $data;
								})) instanceof Fw_Db);
		$this->assertTrue($this->object->Logger instanceof Fw_Logger_Db);
		$this->assertNull($this->object->unsetLogger()->Logger);
	}

}