<?php

/**
 * Test class for Router.
 * Generated by PHPUnit on 2012-04-29 at 23:15:50.
 */
class RouterTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Router
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Router;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Router::setRouteMask
	 */
	public function testSetRouteMask() {
		$this->object->setRouteMask('a');
		
		$this->assertAttributeSame('a', 'routeMask', $this->object);
	}

	/**
	 * @covers Router::parse
	 * @dataProvider parseDataProvider
	 */
	public function testParse($mask, $route, $expected) {
		$this->object->setRouteMask($mask);
		$this->assertEquals($expected, $this->object->parse($route));
	}
	
	public function parseDataProvider() {
		$mask = '/(?<page>[^\/]*)(\/(?<action>[^\/]+))?(\/(?<step>[^\/]+))?/i';
		return array(
			array($mask, '', array('page'=>'')),
			array($mask, '/', array('page'=>'')),
			array($mask, 'sss', array('page'=>'sss')),
			array($mask, 'sss/', array('page'=>'sss')),
			array($mask, 'sss/aaa', array('page'=>'sss', 'action'=>'aaa')),
			array($mask, 'sss/aaa/', array('page'=>'sss', 'action'=>'aaa')),
			array($mask, 'sss/aaa/ccc', array('page'=>'sss', 'action'=>'aaa', 'step'=>'ccc')),
		);
	}

}