<?php

/**
 * Test class for Fw_Db_Query_Behaviour.
 * Generated by PHPUnit on 2011-11-23 at 02:06:43.
 */
class Fw_Db_Query_Behaviour_DeleteTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Fw_Db_Query
	 */
	protected $object;

	/**
	 * 
	 */
	protected function setUp() {
		$this->object = Fw_Db::i()->query()->delete();
	}

	/**
	 * 
	 */
	protected function tearDown() {
		
	}

	public function testSimpleSql() {
		$update = $this->object->from('table_name')->getBehaviour();
		$this->assertEquals('DELETE FROM `table_name`', $update->sql);
	}

	public function testSql() {
		$update = $this->object->from(array('tb'=>'table_name'))->getBehaviour();
		$this->assertEquals('DELETE FROM `table_name` tb', $update->sql);
	}

	public function testSqlWhere() {
		$update = $this->object->from('table_name')->where('a = ?', 100500)->getBehaviour();
		$this->assertEquals('DELETE FROM `table_name` WHERE (a = ?)', $update->sql);
		$this->assertEquals(array(100500), $update->binds);
	}

}